### ISSUE TITLE
ELIC

### ISSUE THREAD

**Issue by battlepeace** [JiangWeibeta/ELIC#1]
On your github homepage, I saw your reproduction of the ELIC model, but I did not find your project code. If your project is open source, can you use your code? I want to learn and improve on this basis. Thank you very much for checking this issue during your busy time. I wish you a smooth and fruitful research.
在您的github主页上，我看到了您对ELIC模型的复现，但我没有找到您的项目代码。如果你的项目是开源的，你能使用你的代码吗？我想在此基础上学习和提高。非常感谢您在繁忙的时间回复这个问题。我祝愿你的研究顺利而富有成果。

**Comment by JiangWeibeta** [comment]
Sorry for the late reply. My original inplementation has some mistakes. My implementation of Residual Bottleneck is wrong. In my original implementation, assuming the channel number of input feature is N, the first 1x1 conv increases the channel number to 2N while in ELIC, the first 1x1 conv decreases the channel number to N/2. I'm now re-training the model, which will take some days. You can refer to https://github.com/Googolxx/STF for channel-wise context implementation and  https://github.com/JiangWeibeta/Checkerboard-Context-Model-for-Efficient-Learned-Image-Compression for checkerboard implementation.

**Comment by battlepeace** [comment]
Thank you very much for your reply. I hope you can share it on github after finishing the experiment. I wish you a smooth research.&nbsp;


赵治衡
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Jiang ***@***.***&gt;; 
发送时间: 2022年12月5日(星期一) 下午2:42
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [JiangWeibeta/ELIC] ELIC (Issue #1)






不好意思，回复晚了。我原来的实施有一些错误。我的残余瓶颈的实现是错误的。在我最初的实现中，假设输入特性的通道数为N，第一个1x1 conv将通道数增加到2N，而在ELIC中，第一个1x1 conv将通道数减少到N/2。我现在重新训练模型，这将需要几天。你可以参考Https://github.com/Googolxx/STF用于信道级上下文实现和Https://github.com/JiangWeibeta/Checkerboard-Context-Model-for-Efficient-Learned-Image-Compression用于棋盘实现。

—
直接回复这封邮件，在GitHub上查看，或取消订阅.
您收到此消息是因为您编写了该线程。消息ID：<江维贝塔/埃利奇/问题/1/1336820891@@GitHub.与&gt;

**Comment by linansheng** [comment]
您好，可以先分享下您复现的模型代码吗

**Comment by linansheng** [comment]
您好，可以分享下您复现的模型代码吗

**Comment by battlepeace** [comment]
Hello, the author, you said last time that there are some problems in the code that need to retrain the model. I don't know whether your code is debugged well now, and if so, whether it can be open source to your GitHub. Thank you very much.
